apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mypolicy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: myrepo
    namespace: flux-system
  policy:
    semver:
      range: .*